package objectRepository;

public class CatalogPage_OR {
    public static final String CATALOGPAGE_HOMEICN = ".icon-home";
    public static final String CATALOGPAGE_NAVIGATION_PIPE = ".navigation-pipe";
//    public static final String CATALOGPAGE_NAVIGATION_PIPE = ".navigation-pipe:nth-of-type(1)"); //to find firs pipe
    public static final String CATALOGPAGE_WOMAN_TAB = "#columns>div.breadcrumb.clearfix>a:nth-child(3)";
//    public static final String CATALOGPAGE_WOMAN_TAB = "//*[@id="columns"]/div[1]/a[2]";
    public static final String CATALOGPAGE_DRESSES_TAB = "#columns>div.breadcrumb.clearfix>a:nth-child(5)";
//    public static final String CATALOGPAGE_DRESSES_TAB = "//*[@id="columns"]/div[1]/a[3]";
    public static final String CATALOGPAGE_EVENING_DRESSES_TAB = "//*[@id='columns']/div[1]/text()[last()]";
    // left sidebar elements
    public static final String CATALOGPAGE_NAVIGATIONMENU_COLUMN = "#left_column";
    public static final String CATALOGPAGE_LAYERSFORM_TITLE = "//*[text()='Catalog']";
    public static final String CATALOGPAGE_LAYERSFORM_MENU_BOX = "#layered_form";
    public static final String CATALOGPAGE_CATALOGMENU_SUBTITLE = "//*[text()='Size']";
    public static final String CATALOGPAGE_SIZE_CHECKBOX = "//*[@id=''uniform-layered_id_attribute_group_1']";
    public static final String CATALOGPAGE_SIZE_LABEL = "//*[text()='S']";
    public static final String CATALOGPAGE_SIZE_M_CHECKBOX = "//*[@id='uniform-layered_id_attribute_group_2']";
    public static final String CATALOGPAGE_SIZE_M_LABEL = "//*[text()='M']";
    public static final String CATALOGPAGE_SIZE_L_CHECKBOX = "//*[@id='uniform-layered_id_attribute_group_3']";
    public static final String CATALOGPAGE_SIZE_L_LABEL = "//*[text()='L']";
    public static final String CATALOGPAGE_COLORS_CATALOGMENU_SUBTITLE = "//*[text()='Color']";
    public static final String CATALOGPAGE_COLORS_FORMMENU_BOX = "#ul_layered_id_attribute_group_3";
    public static final String CATALOGPAGE_COLORS_OPTIONS_CHECKBOXES = ".color-option";
//    @FindBy(xpath = "//*[text()='Color']/../../ul/li/input[@class=\"color-option  \"]";
    public static final String CATALOGPAGE_COLORS_OPTIONS_LABELS = "//*[text()='Color']/../../ul/li/label/a/text()";
    public static final String CATALOGPAGE_COMPOSITIONS_CATALOGMENU_SUBTITLE = "//*[text()='Compositions']";
    public static final String CATALOGPAGE_COMPOSITIONS_OPTIONS_CHECKBOX = "#uniform-layered_id_feature_3";
    public static final String CATALOGPAGE_COMPOSITIONS_OPTIONS_LABELS = "//*[@id='ul_layered_id_feature_5']/li/label/a/text()";
    public static final String CATALOGPAGE_STYLES_CATALOGMENU_SUBTITLE = "//*[text()='Styles']";
    public static final String CATALOGPAGE_STYLES_OPTIONS_CHECKBOX = "//*[text()='Styles']/../../ul/li/div[@class='checker']";
    public static final String CATALOGPAGE_STYLES_OPTIONS_LABELS = "//*[text()='Styles']/../../ul/li/label";
    public static final String CATALOGPAGE_PROPERTIES_CATALOGMENU_SUBTITLE = "//*[text()='Properties']";
    public static final String CATALOGPAGE_PROPERTIES_OPTIONS_CHECKBOX = "//*[text()='Properties']/../../ul/li/div[@class=''checker']";
    public static final String CATALOGPAGE_PROPERTIES_OPTIONS_LABEL = "//*[text()='Properties']/../../ul/li/label";
    public static final String CATALOGPAGE_AVAILBCATALOG_MENU_SUBTITLE = "//*[text()='Availability']";
    public static final String CATALOGPAGE_AVAILBOPTIOS_CHECKBOX = "//*[text()='Availability']/../../ul/li/div[@class='checker']";
    public static final String CATALOGPAGE_AVAILBOPTIONS_LABELS = "//*[text()='Availability']/../../ul/li/label";
    public static final String CATALOGPAGE_MANUFCATALOG_MENU_SUBTITLE = "//*[text()='Manufacturer']";
    public static final String CATALOGPAGE_MANUF_OPTIONS_CHECKBOX  = "//*[text()='Manufacturer']/../../ul/li/div[@class='checker']";
    public static final String CATALOGPAGE_MANUFOPTIONS_LABELS = "//*[text()='Manufacturer']/../../ul/li/label";
    public static final String CATALOGPAGE_CONDITIONS_CATALOG_MENU_SUBTITLE = "//*[text()='Condition']";
    public static final String CATALOGPAGE_CONDITIONS_OPTIONS_CHECKBOX = "//*[text()='Condition']/../../ul/li/div[@class='checker']";
    public static final String CATALOGPAGE_CONDITIONS_OPTIONS_LABELS = "//*[text()='Condition']/../../ul/li/label";
    public static final String CATALOGPAGE_PRICE_CATALOG_MENU_SUBTITLE = "//*[text()='Price']";
    public static final String CATALOGPAGE_PRICE_RANGE_LABELS = "//*[text()='Price']/../../ul/label";
    public static final String CATALOGPAGE_PRICE_RANGE = "#layered_price_range";
    public static final String CATALOGPAGE_PRICE_RANGE_SLIDER = ".layered_slider_container";
    public static final String CATALOGPAGE_INFORMATION_CATALOG_MENU_SUBTITLE = "//*[@class='block informations_block_left']";
    public static final String CATALOGPAGE_DELIVERY_INFORMATION_MENU_TITLE = "//*[@title='Delivery']";
    public static final String CATALOGPAGE_LEGALNOTICE_INFORMATION_MENU_TITLE = "//*[@title='Legal Notice']";
    public static final String CATALOGPAGE_TERM_CONDITIONS_INFORMATION_MENU_TITLE = "//*/*/div[@class='block_content list-block']//a[@title='Terms and conditions of use']";
    public static final String CATALOGPAGE_ABOUTUS_INFORMATION_MENU_TITLE = "//*/div[@class='block_content list-block']//a[@title= 'About us']";
    public static final String CATALOGPAGE_SECURE_PAYMENT_INFORMATION_MENU_TITLE = "//*[@title='Secure payment']";
    public static final String CATALOGPAGE_OUR_STORES_INFORMATION_MENU_TITLE = "//*[@id='informations_block_left_1']/div/ul/li[6]/a";
    public static final String CATALOGPAGE_SPECIALS_CATALOG_MENU_TITLE = "//*[@title='Specials']";
    public static final String CATALOGPAGE_ITEM_IMG_SPECIALS_CATALOG_MENU = "//*[@id='special_block_right']//img";
    public static final String CATALOGPAGE_ITEM_NAME_SPECIALS_CATALOG_MENU = "div.product-content>h5>a.product-name";
    public static final String CATALOGPAGE_ITEM_DESCR_SPECIALS_CATALOG_MENU = "div.product-content>p.product-description";
    public static final String CATALOGPAGE_ITEM_PRICEBOX_SPECIALS_CATALOG_MENU = "div.product-content>div.price-box";
    public static final String CATALOGPAGE_ITEM_PRICE_SPECIALS_CATALOG_MENU = "div.product-content>div.price-box>span.price";
    public static final String CATALOGPAGE_ITEM_OLD_PRICE_SPECIALS_CATALOG_MENU = "div.product-content>div.price-box>span.old-price";
    public static final String CATALOGPAGE_ALL_SPECIALS_CATALOG_MENU = "//*[@title='All specials']";
    public static final String CATALOGPAGE_CATALOG_MENU_OUR_STORES_SUBTITLE = "//*[@class='title_block']/a[@title='Our stores']";
    public static final String CATALOGPAGE_CATALOG_MENU_OUR_STORES_IMG = "#stores_block_left>div>p>a>img.img-responsive";
    public static final String CATALOGPAGE_CATALOG_MENU_OUR_STORES_LINK = "//*[text()='Discover our stores']";
    public static final String CATALOGPAGE_CATALOG_MENU_VIEWED_PRODS_SUBTITLE = "//*[text()='Viewed products']";
    public static final String CATALOGPAGE_CATALOG_MENU_VIEWED_PRODS_IMG = ".products-block-image";
    public static final String CATALOGPAGE_CATALOG_MENU_VIEWED_PRODS_CONTENT = "//*[@class='clearfix last_item']/div[@class='product-content']";
    public static final String CATALOGPAGE_CATALOG_MENU_VIEWED_PRODS_NAME = "//*[@class='clearfix last_item']//p[@class='product-description']";

    //  main page column
    public static final String CATALOGPAGE_MAINPAGECOLUMN = "#center_column.center_column";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_CATEGORY_IMG = ".content_scene_cat";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_CATEGORY_NAME = ".cat-name";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_PRODUCTSCOUNTER = ".heading-counter";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_FILTER_LABEL = "//*[@class='select selector1']/label";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_PRODUCTSELECTOR_FLD = "#uniform-selectProductSort";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_DISPLAYVIEWED_TITLE = "//*[text()='View']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_GRID_ICON = "#grid";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_GRID_TITLE = "//*[text() = 'Grid']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_LIST_ICON = ".icon-th-list";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_LIST_TITLE = "//*[text() = 'List']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_PRODUCT_COUNTER = "//*/div[@class='top-pagination-content clearfix']//div[@class=''product-count']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_COMPARE_BTN = "//*/button[@class='btn btn-default button button-medium bt_compare bt_compare']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_COMPARE_BTNVALUE = "//*/div[@class='top-pagination-content clearfix']//strong[@class='total-compare-val']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_RIGHT_ARROW_VAL = "//*/div[@class='top-pagination-content clearfix']//i[@class='icon-chevron-right right']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ITEM_PHOTO = ".product_img_link>img.replace-2x.img-responsive";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_PREVIEW_PHOTO = ".icon-eye-open";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ITEMPIC = "//*[@id='bigpic']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ITEM_VIEWBLOCK = "//*[@id=''views_block']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ITEM_VIEWBLOCK_PICLIST = "//*[@id='thumbs_list']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ITEM_VIEWBLOCK_PIC1 = "a.fancybox.shown";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ITEM_VIEWBLOCK_PIC2 = "a.fancybox.shown";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ITEM_VIEWBLOCK_CLOSE_BTN = "a.fancybox-item.fancybox-close";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_PRODUCTNAME_TITLE = ".right-block>h5>a.product-name";
//    public static final String CATALOGPAGE_MAINPAGECOLUMN_PRODUCTNAME_TITLE = "//*[@class = \"right-block\"]//a[@class=\"product-name\"]";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ITEM_PRICE = "div.right-block>div>.price.product-price";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ADDTOCART = "//*[text() = 'Add to cart']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_MORE_BTN = "//*[text() = 'More']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_COLORLIST_CONTAINER = ".color-list-container";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_COLORITEM_VARIABLE = ".color_pick";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_COLORITEM1_VARIABLE = "#color_1";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_INSTOCK_BTN = ".available-now";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ADDTOWISGLIST_LINK = ".addToWishlist";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_ADDTOCOMPARE_LINK = ".compare";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_PRODUCT_COUNTER_BOTTOM = "//*/div[@class='content_sortPagiBar']//div[@class='product-count']";
    public static final String CATALOGPAGE_MAINPAGECOLUMN_COMPARE_BTN_BOTTOM = "//*[@class='bottom-pagination-content clearfix']//button";
}
