package objectRepository;

public class PersonalInfoPage_OR {
    public static final String PERSONALINFOPAGE_HOMEICN = ".icon-home";
    public static final String PERSONALINFOPAGE_NAVIGATION_PIPE1 = "//*/span[@class='navigation-pipe'][1]";
    public static final String PERSONALINFOPAGE_NYACCOUNT_TAB = "//*/div[@class='breadcrumb clearfix']/a[2]";
    public static final String PERSONALINFOPAGE_NAVIGATION_PIPE2 = "//*/span[@class='navigation-pipe'][2]";
    public static final String PERSONALINFOPAGE_PERSONALINFO_TAB = "span.navigation_page";
    public static final String PERSONALINFOPAGE_TITLE = "//h1[contains(text(),'Your personal information')]";
    public static final String PERSONALINFOPAGE_UPDATE_MSG = "//*/p[contains(text(),'if it has changed.')]";
    public static final String PERSONALINFOPAGE_REQUIRED_MARK = "//p[@class='required']";
    public static final String PERSONALINFOPAGE_MAILGENDERRADIO_LABEL = "//label[@for='id_gender1']";
    public static final String PERSONALINFOPAGE_MAILGENDERRADIO_BTN = "//div[@id='uniform-id_gender1']";
    public static final String PERSONALINFOPAGE_FEMAILGENDERRADIO_LABEL = "//label[@for='id_gender2']";
    public static final String PERSONALINFOPAGE_FEMAILGENDERRADIO_BTN = "//div[@id='uniform-id_gender2']";
    public static final String PERSONALINFOPAGE_FIRSTNAME_LABEL = "//label[@for='firstname']";
    public static final String PERSONALINFOPAGE_FIRSTNAME_FLD = "//input[@id='firstname']";
    public static final String PERSONALINFOPAGE_LASTNAME_LABEL = "//label[@for='lastname']";
    public static final String PERSONALINFOPAGE_LASTNAME_FLD = "//input[@id='lastname']";
    public static final String PERSONALINFOPAGE_EMAILADDRESS_LABEL = "//label[@for='email']";
    public static final String PERSONALINFOPAGE_EMAILADDRESS_FLD = "//input[@id='email']";
    public static final String PERSONALINFOPAGE_BIRTHDATA_LABEL = "//label[contains(text(),'Date of Birth')]";
    public static final String PERSONALINFOPAGE_BIRTHDATA_DAY_SELECTOR = "//div[@id='uniform-days']";
    public static final String PERSONALINFOPAGE_BIRTHDATA_DAY_CHOOSER = "//select[@id='days']/option[@selected='selected']";
    public static final String PERSONALINFOPAGE_BIRTHDATA_MONTH_SELECTOR = "//div[@id='uniform-months']";
    public static final String PERSONALINFOPAGE_BIRTHDATA_MONTH_CHOOSER = "//select[@id='months']/option[@selected='selected']";
    public static final String PERSONALINFOPAGE_BIRTHDATA_YEARS_SELECTOR = "//div[@id='uniform-years']";
    public static final String PERSONALINFOPAGE_BIRTHDATA_YEARS_CHOOSER = "//div[@id='uniform-years']//option[@selected='selected']";
    public static final String PERSONALINFOPAGE_CURRENTPASSWD_LABEL = "//label[@for='old_passwd']";
    public static final String PERSONALINFOPAGE_CURRENTPASSWD_FLD = "//input[@id='old_passwd']";
    public static final String PERSONALINFOPAGE_NEWPASSWD_LABEL = "//label[contains(text(),'Social title')]";
    public static final String PERSONALINFOPAGE_NEWPASSWD_FLD = "//input[@id='passwd']";
    public static final String PERSONALINFOPAGE_CONFIRMATION_LABEL = "//div[@class='password form-group']/label[@for='confirmation']";
    public static final String PERSONALINFOPAGE_CONFIRMATION_FLD = "//input[@id='confirmation']";
    public static final String PERSONALINFOPAGE_NEWSLETTERS_LABEL = "//label[@for='newsletter']']";
    public static final String PERSONALINFOPAGE_NEWSLETTERS_CHECKBOX = "//div[@id='uniform-newsletter']";
    public static final String PERSONALINFOPAGE_SPECIALOFFERS_LABEL = "//label[@for= 'optin']";
    public static final String PERSONALINFOPAGE_SPECIALOFFERS_CHECKBOX = "//div[@id= 'uniform-optin']";
    public static final String PERSONALINFOPAGE_SAVE_BTN = "//button[@name= 'submitIdentity']";
    //    public static final String PERSONALINFOPAGE_SAVE_BTN = "//span[text()= 'Save']";
    public static final String PERSONALINFOPAGE_SAVE_BTN_ARROW = "//button[@name='submitIdentity']//i[@class= 'icon-chevron-right right']";
    public static final String PERSONALINFOPAGE_BACK_BTNS = "//ul[@class='footer_links clearfix']//a[@class='btn btn-default button button-small']";
    public static final String PERSONALINFOPAGE_BACKBTNS_ARROWS = "//ul[@class='footer_links clearfix']//a[@class='btn btn-default button button-small']/span/i";
}
