package objectRepository;

public class SearchResultsPage_OR {
    public static final String HOME_ICN =".icon-home";
    public static final String NAVIGATION_PIPE = ".navigation-pipe";
    public static final String NAVIGATION_TAB = ".navigation-page";
    public static final String SEARCH_TITLE = "//h1[@class='page-heading  product-listing'][contains(text(), 'Search')]";
    public static final String SEARCHTITLE_LIGHTER = "//span[@class='lighter']";
    public static final String SORTBY_LABEL = "//label[@for='selectProductSort']";
    public static final String SORTBY_SELECTOR = "//select[@id='selectProductSort']";
//    public static final String SORTBY_SELECTOR = "//div[@id='uniform-selectProductSort']";
    public static final String FOUNDEDRESULTS_HEADING_COUNTER = "//span[@class='heading-counter']";
    public static final String FOUNDEDRESULTS_VIEW_OPTIONS = "//li[@class='display-title']";
    public static final String FOUNDEDRESULTS_GRIDVIEW_OPTIONS = "//li[@id='grid']//a[contains(text(), 'Grid')]";
    public static final String FOUNDEDRESULTS_LISTVIEW_OPTIONS = "//li[@id='list']//a[contains(text(), 'List')]";
    public static final String FOUNDEDRESULTS_SHOWING_COUNTER = "//*[@class='top-pagination-content clearfix']/div[@class='product-count'][contains(text(),'Showing')]";
    public static final String FOUNDEDRESULTS_SEARCH_LIGHTER = "//div[@class='left-block']//a[@class='product_img_link']";
    public static final String FOUNDEDRESULTS_COMPARE_BTN = "//*[@id='center_column']/div[1]/div[2]/form/button";
    public static final String FOUNDEDRESULTS_PRODUCT_LIST_CONTAINER = "//ul[@class='product_list grid row']";
    public static final String FOUNDEDRESULTS_FIRSTPRODUCT_CONTAINER = "(//div[@class='product-container'])[1]";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_IMG = "(//div[@class='product-container'])[1]//a[@class='product_img_link']";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_IMG_PREVIEW_ICN = "(//div[@class='product-container'])[1]//I[@class='icon-eye-open']";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_PRODUCT_NAME = "((//div[@class='product-container'])[1]//a[@class='product-name']";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_PRODUCT_PRICE = "//*[@id='center_column']/ul/li[1]/div/div[2]/div[1]/span[1]";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_PRODUCT_OLDPRICE = "//*[@id='center_column']/ul/li[1]/div/div[1]/div/div[2]/span[2]";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_PRODUCT_DISCOUNT = "//*[@id='center_column']/ul/li[1]/div/div[1]/div/div[2]/span[3]";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_ADDTOCART_BTN = "(//div[@class='product-container'])[1]//span[text()='Add to cart']";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_MORE_BTN = "(//div[@class='product-container'])[1]//span[text()='More']";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_COLORS_OPTIONS = "(//div[@class='product-container'])[1]//ul[@class='color_to_pick_list clearfix']";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_SECOND_COLORS_OPTION = "(//div[@class='product-container'])[1]//ul[@class='color_to_pick_list clearfix']/li[2]";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_INSTOCK_BTN = "(//div[@class='product-container'])[1]//span[@class='available-now']";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_ADTOWISHLIST_LINK = "(//div[@class='product-container'])[1]//a[contains(text(),'Add to Wishlist')]";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_ADTOCOMPARE_LINK = "(//div[@class='product-container'])[1]//div[@class='compare']";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_BOTTOM_COUNTER = "//div[@class='bottom-pagination-content clearfix']//div[@class='product-count']";
    public static final String FOUNNDEDRESULTS_FIRSTPRODUCT_BOTTOM_COMPARE_BTN = "//div[@class='bottom-pagination-content clearfix']//FORM[@class='compare-form']/button";

    public static final String TOP_SELLERS_LEFT_BLOCK = "//div[@id='best-sellers_block_right']";
    public static final String TOP_SELLERS_LEFT_BLOCK_TITLE = "//h4[@class='title_block']";
//    public static final String TOP_SELLERS_LEFT_BLOCK_TITLE = "//a[text()='Top sellers']";
    public static final String TOP_SELLERS_LEFT_BLOCK_CONTENT = "//div[@id='best-sellers_block_right']/div[@class='block_content']";
    public static final String TOP_SELLERS_BLOCK_CONTENT_FIRST_ITEM = "//div[@id='best-sellers_block_right']/div[@class='block_content']//li[1]";
    public static final String TOP_SELLERS_BLOCK_CONTENT_FIRST_ITEM_IMG = "//div[@id='best-sellers_block_right']/div[@class='block_content']//li[1]/a";
    public static final String TOP_SELLERS_BLOCK_CONTENT_FIRST_ITEM_NAME = "//div[@id='best-sellers_block_right']/div[@class='block_content']//li[1]/div/h5";
    public static final String TOP_SELLERS_BLOCK_CONTENT_FIRST_ITEM_DESCRIPTION = "//*[@id='best-sellers_block_right']/div/ul/li[1]/div/p";
    public static final String TOP_SELLERS_BLOCK_CONTENT_FIRST_ITEM_PRICE = "//div[@id='best-sellers_block_right']/div[@class='block_content']//li[1]/div/div[@class='price-box']";
    public static final String ALL_BEST_SELLERS_BTN = "//a[@title='All best sellers']";
    public static final String ALL_BEST_SELLERS_BTN_RIGHT_ICN = "//a[@title='All best sellers']//i";
    public static final String CATEGORIES_LEFT_BLOCK = "//div[@id='categories_block_left']";
    public static final String CATEGORIES_LEFT_BLOCK_TITLE = "//h2[@class='title_block']";
    public static final String CATEGORIES_LEFT_BLOCK_CONTENT = "//div[@id='categories_block_left']/div";
    public static final String CATEGORIES_LEFT_BLOCK_CONTENT_PLUS_BTN = "//div[@class='block_content']/ul/li/span[@class='grower CLOSE']";
    public static final String CATEGORIES_LEFT_BLOCK_CONTENT_TOP = "//*[@id='categories_block_left']/div/ul/li/ul/li[1]";
    public static final String CATEGORIES_LEFT_BLOCK_CONTENT_TOP_PLUS_BTN = "//*[@id='categories_block_left']/div/ul/li/ul/li[1]/span";
    public static final String INFORMATION_LEFT_BLOCK = "//section[@id='informations_block_left_1']";
    public static final String INFORMATION_LEFT_BLOCK_TITLE = "//*/p[@class='title_block']/a[contains(text(),'Information')]";
    public static final String INFORMATION_LEFT_BLOCK_CONTENT = "//div[@class='block_content list-block']";
    public static final String INFORMATION_LEFT_BLOCK_CONTENT_PLUS_ABOUT_US_SUBCATEGORY = "//div[@class='block_content list-block']//a[@title='About us']";
    public static final String MANUFACTURES_LEFT_BLOCK = "//div[@id='manufacturers_block_left']";
    public static final String MANUFACTURES_LEFT_BLOCK_TITLE = "//div[@id='manufacturers_block_left']/p";
    public static final String MANUFACTURES_LEFT_BLOCK_CONTENT = "//div[@id='manufacturers_block_left']/div";
    public static final String MANUFACTURES_LEFT_BLOCK_FASHION = "//div[@id='manufacturers_block_left']/div//li";
    public static final String MANUFACTURES_LEFT_BLOCK_FASHION_LINK = "//div[@id='manufacturers_block_left']/div//li/a";
    public static final String MANUFACTURES_LEFT_BLOCK_ALL_LIST = "//div[@id='manufacturers_block_left']//select";
    public static final String MANUFACTURES_LEFT_BLOCK_ALL_LIST_FASHION_OPTION = "//div[@id='manufacturers_block_left']//select/option[2]";
    public static final String SPECIALS_LEFT_BLOCK = "//div[@id='special_block_right']";
    public static final String SPECIALS_LEFT_BLOCK_TITLE = "//div[@id='special_block_right']//a[@title='Specials']";
    public static final String SPECIALS_LEFT_BLOCK_CONTENT = "//div[@id='special_block_right']/div";
    public static final String SPECIALS_LEFT_BLOCK_PRODUCT_IMG = "//div[@id='special_block_right']/div//a[@class='products-block-image']";
    public static final String SPECIALS_LEFT_BLOCK_PRODUCT_CONTENT = "//div[@id='special_block_right']/div//div[@class='product-content']";
    public static final String SPECIALS_LEFT_BLOCK_PRODUCT_PRICE = "//div[@id='special_block_right']/div//div[@class='product-content']/div";
    public static final String SPECIALS_LEFT_BLOCK_ALL_SPECIALS_BTN = "//div[@id='special_block_right']//span[text() ='All specials']";
    public static final String OUR_STORES_LEFT_BLOCK = "//div[@id='stores_block_left']']";
    public static final String OUR_STORES_LEFT_BLOCK_TITLE = "//div[@id='stores_block_left']/p";
    public static final String OUR_STORES_LEFT_BLOCK_CONTENT = "//div[@class='block_content blockstore']";
    public static final String OUR_STORES_LEFT_BLOCK_PRODUCT_IMG = "//div[@class='block_content blockstore']/p";
    public static final String OUR_STORES_LEFT_BLOCK_PRODUCT_DISCOVER_BTN = "//div[@class='block_content blockstore']//span";
    public static final String OUR_STORES_LEFT_BLOCK_PRODUCT_DISCOVER_BTN_ICN = "//div[@class='block_content blockstore']//span/i";
    public static final String SUPPLIERS_LEFT_BLOCK = "//div[@id='suppliers_block_left']";
    public static final String SUPPLIERS_LEFT_BLOCK_TITLE = "//div[@id='suppliers_block_left']//a[@title='Suppliers']";
    public static final String SUPPLIERS_LEFT_BLOCK_CONTENT = "//div[@id='suppliers_block_left']//div[@class='block_content list-block']";
    public static final String SUPPLIERS_LEFT_BLOCK_FASHION_SUPPLIER = "//div[@id='suppliers_block_left']//div[@class='block_content list-block']//li";
    public static final String SUPPLIERS_LEFT_BLOCK_ALL_SUPPLIERS_DROPDOWN = "//div[@id='suppliers_block_left']//div[@class='block_content list-block']//select";
    public static final String SUPPLIERS_LEFT_BLOCK_ALL_SUPPLIERS_OPTION = "//div[@id='suppliers_block_left']//div[@class='block_content list-block']//select/option";
    public static final String VIEWED_PRODUCTS_LEFT_BLOCK = "//div[@id='viewed-products_block_left']";
    public static final String VIEWED_PRODUCTS_LEFT_BLOCK_TITLE = "//div[@id='viewed-products_block_left']/p";
    public static final String VIEWED_PRODUCTS_LEFT_BLOCK_CONTENT = "//div[@id='viewed-products_block_left']/div";
    public static final String VIEWED_PRODUCTS_LEFT_BLOCK_LAST_VIEWED_ITEM = "//div[@id='viewed-products_block_left']/div//li";
    public static final String VIEWED_PRODUCTS_LEFT_BLOCK_LAST_VIEWED_ITEM_IMG = "//div[@id='viewed-products_block_left']/div//li/a";
    public static final String VIEWED_PRODUCTS_LEFT_BLOCK_LAST_VIEWED_ITEM_DESC = "//div[@id='viewed-products_block_left']/div//li//p";
}
